Notebook tests and a small gait refactor
biomarkersParkinson/paradigma pull request #15
Opened 2024-03-26 10:00 UTC by vedran-kasalica

Introduce Notebook tests using `papermill`

- Introduce `papermill` dependency
- Setup tests for the notebooks

2024-04-15 09:44 UTC, vedran-kasalica commented
I made some slight changes and uploaded notebook tests. @Erikpostt could you test `4.extract_features_arm_swing`? It is failing and I am not sure why.

2024-04-15 12:05 UTC, Erikpostt commented
> I made some slight changes and uploaded notebook tests. @Erikpostt could you test `4.extract_features_arm_swing`? It is failing and I am not sure why.

Hi @vedran-kasalica, I think I resolved the issue in the recent commit, but please verfiy. It had to do with channel names, which I've now standardized to accelerometer/gyroscope instead of acceleration/rotation, which I think it a more accurate and reasonable representation of the channels. This also modified the test data.

2024-04-15 12:16 UTC, vedran-kasalica commented
> > I made some slight changes and uploaded notebook tests. @Erikpostt could you test `4.extract_features_arm_swing`? It is failing and I am not sure why.
> 
> Hi @vedran-kasalica, I think I resolved the issue in the recent commit, but please verfiy. It had to do with channel names, which I've now standardized to accelerometer/gyroscope instead of acceleration/rotation, which I think it a more accurate and reasonable representation of the channels. This also modified the test data.

Thanks, @Erikpostt, it runs fine now, including the papermill tests.

2024-04-15 12:18 UTC, vedran-kasalica commented
@Erikpostt could you also confirm whether Notebook 5 runs for you?

2024-04-15 16:03 UTC, Erikpostt commented
> @Erikpostt could you also confirm whether Notebook 5 runs for you?

Should be fixed now.

2024-04-16 12:11 UTC, vedran-kasalica commented
> > @Erikpostt could you also confirm whether Notebook 5 runs for you?
> 
> Should be fixed now.

Thanks, it works now!

2024-04-17 14:08 UTC, kretep requested changes
Looks good, just some minor issues in the tests for the notebooks

2024-04-17 14:08 UTC, kretep commented on tests/test_notebooks.py
> +def create_tmp_folder_if_not_exists(base_path: str):
Why is this used when always using shared_datadir? Isn't the shared_datadir always present?

2024-04-17 14:08 UTC, kretep commented on tests/test_notebooks.py
> +    shared_datadir : str
I think the type of shared_datadir is Path

2024-04-17 14:08 UTC, kretep commented on tests/test_notebooks.py
> +    shared_datadir : str
Although I don't think the shared_datadir gets injected here (it's not a top-level test function, but a method that is called), so maybe rename it to something else to avoid confusion. It could be any path. And if only called with shared_datadir as parameter, the type will be Path here also

2024-04-17 14:08 UTC, kretep commented on tests/test_notebooks.py
> +    for metadata, binary in biaries_pairs:
missing an n here

2024-04-17 14:13 UTC, vedran-kasalica commented on tests/test_notebooks.py
> +def create_tmp_folder_if_not_exists(base_path: str):
Yes, but I was getting an error when the `tmp` folder inside of it was not explicitly created (that's where we store the temp Notebook outputs).

2024-04-17 14:32 UTC, kretep commented on tests/test_notebooks.py
> +def create_tmp_folder_if_not_exists(base_path: str):
What is the reasoning behind that? I only see that the 5th notebook writes to a 'tmp' folder

2024-04-17 14:38 UTC, vedran-kasalica commented on tests/test_notebooks.py
> +def create_tmp_folder_if_not_exists(base_path: str):
They all do, all the notebook test outputs are written to the `data/tmp` folder. Mostly to distinguish it from the original data folder and to allow easier manual comparisons when needed. I just decided to use the `tmp` folder to be able to mirror the existing Notebook output structure.

2024-04-17 17:59 UTC, vedran-kasalica commented on tests/test_notebooks.py
> +    shared_datadir : str
I fixed it.

2024-04-17 17:59 UTC, vedran-kasalica commented on tests/test_notebooks.py
> +    shared_datadir : str
I agree, I fixed it.

2024-04-17 17:59 UTC, vedran-kasalica commented on tests/test_notebooks.py
> +    for metadata, binary in biaries_pairs:
I fixed it.

2024-04-18 12:25 UTC, kretep approved these changes

2024-04-18 12:26 UTC, merged