Create files for tremor pipeline
biomarkersParkinson/paradigma pull request #69
Opened 2024-10-11 13:43 UTC by nienketimmermans

2024-10-11 14:41 UTC, Erikpostt commented on docs/notebooks/tremor.ipynb
> +   "execution_count": 15,
Hier zie je een execution count staan: als je naar je notebook gaat, die je een getal (15) tussen vierkant [] haakjes staan. Dit is een counter voor hoeveel cellen je gedraaid hebt. Het is netjes om voor je push even _restart_ en _clear all outputs_ te klikken bovenin.

2024-10-11 14:41 UTC, Erikpostt commented on docs/notebooks/tremor.ipynb
> +    "Tremor analysis"
```suggestion
    "# Tremor analysis"
```

2024-10-11 14:43 UTC, Erikpostt commented on docs/notebooks/tremor.ipynb
> +    "Tremor analysis"
Om titels te maken van markdown, kan je hekjes (#) invoegen vóór de tekst. Één hekje is een grote titel, meerdere hekjes maken de titel steeds kleiner.

2024-10-11 14:43 UTC, Erikpostt commented on docs/notebooks/tremor.ipynb
> +      "The autoreload extension is already loaded. To reload it, use:\n",
Hier heb je ook nog output. Met _Clear all outputs_ bovenin gaat ook dit weg.

2024-10-11 14:44 UTC, Erikpostt requested changes
Goed begin! Een paar kleine suggesties, probeer ze vooral eens uit. Als je die opgelost hebt zal ik het mergen.

2024-10-15 07:47 UTC, nienketimmermans commented
Ik heb je suggesties toegepast en de eerste test gedraaid voor de preprocessed data

2024-10-15 08:14 UTC, Erikpostt commented on tests/test_tremor_analysis.py
Zou je deze misschien in een nieuw bestand kunnen zetten, bijvoorbeeld: _tests/test_data_preparation_. Dan kunnen daar de IMU en PPG tests in -- ze vallen volgens deze diagram (https://docs.google.com/spreadsheets/d/19AZZ44cOJeHonGaSpAPh0eMXW2ix5JHz9L9zYTNnH6g/edit?gid=2120810428#gid=2120810428) ook buiten de domeinen.

2024-10-15 08:15 UTC, Erikpostt commented on tests/data/2.preprocessed_data/tremor/accelerometer_meta.json
> +                0.06097561
Volgens mij kloppen deze scale factors niet (ze matchen iig niet met de channels). Wellicht wil je deze überhaupt niet meer opslaan na het preprocessen?

2024-10-15 08:15 UTC, Erikpostt commented on tests/data/2.preprocessed_data/tremor/gyroscope_meta.json
> +            ]
Deze kloppen ook niet helemaal -- ik zou ze wellicht gewoon weghalen.

2024-10-15 11:39 UTC, Erikpostt commented on docs/notebooks/tremor/tremor.ipynb
Sorry, bijna! Je hebt nog steeds een _execution count_ staan van de cellen in de notebook.

2024-10-15 11:40 UTC, Erikpostt requested changes
Nog één klein dingetje (de execution count), dan klaar om te mergen.

2024-10-15 12:44 UTC, nienketimmermans commented
Als het goed is nu eindelijk opgelost ;)

2024-10-15 12:46 UTC, Erikpostt approved these changes

2024-10-15 12:46 UTC, merged