Add gait weekly aggregates
biomarkersParkinson/paradigma pull request #84
Opened 2024-12-10 11:56 UTC by Erikpostt

The purpose of this PR is to add (weekly) aggregates stratified by segment category to the gait pipeline as a final step. The current implementation stores a `.json` file with the arm swing parameters for different segment duration categories and overall.

In the process of adding this feature, the following was modified:
- Path variable names standardized to _path_to_X_
- Notebook testing removed as it is does not fit the purpose of the release (more on this below)
- Column names standardized to `DataColumns` in _constants.py_ instead of `config`. 

### Notebook testing
The purpose of notebook testing was to ensure that the data generated in the notebooks was equal (up to a margin) to simulated data. The IO of high-level functions is currently managed inside _test_gait_analysis.py_, _test_ppg_analysis_ and _test_tremor_analysis_. Added that we should restructure the notebooks such that its goal is not to create test data, but to document and demonstrate the functionalities of Paradigma, I think we should remove the notebook testing. Furthermore note that only the _gait_ pipeline used this functionality.

2024-12-10 12:04 UTC, Erikpostt commented
@nienketimmermans if approved, don't forget to merge these changes into #81

2024-12-10 15:55 UTC, nienketimmermans requested changes
@Erikpostt I fixed some 'path_to...' typos and added a minor suggestion to provide more explanation. After you've looked at that it's ready to be merged.

2024-12-10 15:55 UTC, nienketimmermans commented on src/paradigma/gait/gait_analysis.py
> +    df_segments = discard_segments(
I would add more explanation here.

2024-12-10 15:55 UTC, nienketimmermans commented on src/paradigma/gait/gait_analysis.py
> +    df_segments[DataColumns.SEGMENT_CAT] = categorize_segments(df_segments, config, 'windows')
Here as well

2024-12-11 09:33 UTC, nienketimmermans approved these changes

2024-12-11 09:33 UTC, merged