Create prepared data
biomarkersParkinson/paradigma pull request #88
Opened 2024-12-13 15:01 UTC by Erikpostt

This is quite a substantial PR, containing disparate changes to the repository. In this PR, I propose to change the following:

### Create prepared data
We have been discussing lately what to do with specific PPP functionalities that were contained inside ParaDigMa. I discussed this issue with Twan, and we agreed that these functionalities could be both (1) path of the toolbox and (2) not in the pipelines. I therefore propose in this PR to create a separate data folder containing prepared data, which contains the raw PPP data with the PPP-specific data preprocessing functions applied. 

### Setting time unit standard to seconds
Throughout the preprocessing steps we have been switching between seconds and milliseconds, and I therefore suggest we provide functionalities for transforming the time arrays using `utils.transform_time_array`, but strictly require the user to prepare the dataset themselves. The requirements for a dataframe shall be part of the documentation/tutorials (PR shall soon be delivered).

2024-12-13 15:10 UTC, Erikpostt commented
Closing briefly to add more comments to the changes, will re-open it soon.

2024-12-13 15:12 UTC, Erikpostt commented on src/paradigma/constants.py
We could also opt for two parameters: 
1. Time set-off: absolute, relative or difference
2. Time units: seconds or milliseconds

2024-12-13 15:13 UTC, Erikpostt commented on src/paradigma/util.py
This file is currently overcrowded with _TSDF_ functionalities. Twan is currently working on an update to _TSDF_ such that we don't need a substantial amount of these functionalities.

2024-12-13 15:24 UTC, Erikpostt commented
@KarsVeldkamp @nienketimmermans ready for review.

2024-12-16 09:46 UTC, nienketimmermans requested changes
Hi Erik, I have added some comments, mainly related to the documentation of functions. I also saw that the time unit of the prepared data is in ms, but transforming it to seconds is already part of the data preparation step right? Otherwise it looks good!

2024-12-16 09:46 UTC, nienketimmermans commented on docs/tutorials/data_preparation.ipynb
> +    "For the Gait & Arm Swing pipeline, it is essential to ensure correct sensor axes orientation. For more information please read [X]. If the sensors are correctly aligned, you can use `invert_watc
I think you mean: If the sensors are **not** correctly aligned, you can...

2024-12-16 09:46 UTC, nienketimmermans commented on src/paradigma/preprocessing.py
> +    This function takes in sensor data, scales the data if scale factors are provided,
This function doesn't use the scale factors anymore, right?

2024-12-16 09:46 UTC, nienketimmermans commented on src/paradigma/preprocessing.py
> +    Preprocesses IMU data by renaming columns, transforming time units, resampling, and applying filters.
Remove 'renaming columns, transforming time units' as this is done elsewhere

2024-12-16 09:46 UTC, nienketimmermans commented on tests/data/1.prepared_data/imu/IMU_meta.json
> +                "time_relative_ms"
Shouldn't this be in seconds?

2024-12-16 09:46 UTC, nienketimmermans commented on tests/data/1.prepared_data/ppg/PPG_meta.json
> +                "time_relative_ms"
Same here

2024-12-16 10:11 UTC, Erikpostt commented
Thank you @nienketimmermans , I have edited the code/data based on your suggestions.

2024-12-16 12:55 UTC, Erikpostt commented
Testing failed while solving invisible bug. Changing to draft to fix the issue.

2024-12-16 13:02 UTC, Erikpostt commented
Ready for review.

2024-12-16 14:41 UTC, nienketimmermans approved these changes

2024-12-31 15:08 UTC, KarsVeldkamp commented on docs/tutorials/data_preparation.ipynb
> +   ]
Is this cell by accident inserted twice or am I missing something?

2024-12-31 15:10 UTC, KarsVeldkamp commented on docs/tutorials/data_preparation.ipynb
> +    "ParaDigMa expects acceleration to be measured in g, and rotation in deg/s. Units can be converted conveniently using ParaDigMa functionalities."
PPG is AU, do we want to mention this or leave it out?

2024-12-31 15:11 UTC, KarsVeldkamp commented on src/paradigma/constants.py
> +    """ The time is the difference between consecutive samples in seconds. """
I guess eventually we want to stick to SI units? And remove the ms options?

2024-12-31 15:20 UTC, KarsVeldkamp commented on src/paradigma/gait/gait_analysis.py
> +    extractor = WindowedDataExtractor(windowed_cols)
Looking good!

2024-12-31 15:24 UTC, KarsVeldkamp commented on src/paradigma/util.py
> +    - The function handles different time units (`TimeUnit.RELATIVE_MS`, `TimeUnit.RELATIVE_S`, `TimeUnit.ABSOLUTE_MS`, `TimeUnit.ABSOLUTE_S`, `TimeUnit.DIFFERENCE_MS`, `TimeUnit.DIFFERENCE_S`).
Makes sense to have this functionality to allow both ms and s for the user

2024-12-31 15:27 UTC, KarsVeldkamp approved these changes
Looking good! Feel free to merge this branch into main, I only have a couple of minor comments but not that relevant...

2024-12-31 15:28 UTC, KarsVeldkamp commented
And I see I have caused conflicts by merging my HR estimation branch first... Apologies...

2025-01-02 07:23 UTC, Erikpostt commented on docs/tutorials/data_preparation.ipynb
> +    "ParaDigMa expects acceleration to be measured in g, and rotation in deg/s. Units can be converted conveniently using ParaDigMa functionalities."
Do you think it has added value, in the sense that there are other units possible and it is useful to report which units are used for the PPG data?

2025-01-02 07:23 UTC, Erikpostt commented on src/paradigma/constants.py
> +    """ The time is the difference between consecutive samples in seconds. """
Agree, I have created an issue (#92) for this so we can clean this up in one of the clean-up PRs coming up next week.

2025-01-02 07:35 UTC, Erikpostt commented
@KarsVeldkamp don't worry about the conflicts, that's natural. Can you take a look at the changes I made to _ppg_preprocessing_ in _preprocessing.py_? I moved some functionalities from this step to the data preparation step, where the functionalities are imported from _util.py_.

2025-01-02 11:15 UTC, merged